server:
  port: 8081
# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cms_admin_sys?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123123

#  security:
#    user:
#      name: user
#      password: 123123

mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

coderlan:
  jwt:
    header: Authorization
    expire: 604800 #7天 秒单位
    secret: scni9aq1931sdnecjdqd3a2dqe24a21df

